# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ikIsCSRO6bNlpbxlImGq6hUQ9V4U2kPF
"""

processes = [
    {"name": "P1", "arrival": 2, "burst": 4},
    {"name": "P2", "arrival": 10, "burst": 1},
    {"name": "P3", "arrival": 3, "burst": 2},
    {"name": "P4", "arrival": 2, "burst": 5},
    {"name": "P5", "arrival": 0, "burst": 5},
]


processes.sort(key=lambda x: (x["arrival"], x["burst"]))

time = 0
completed = []
execution_order = []

while processes:

    ready_queue = [p for p in processes if p["arrival"] <= time]

    if not ready_queue:
        time += 1
        continue
    shortest = min(ready_queue, key=lambda x: x["burst"])
    shortest["start"] = time
    shortest["completion"] = time + shortest["burst"]
    shortest["turnaround"] = shortest["completion"] - shortest["arrival"]
    shortest["waiting"] = shortest["turnaround"] - shortest["burst"]


    time += shortest["burst"]
    execution_order.append(shortest["name"])
    completed.append(shortest)
    processes.remove(shortest)


print("\nExecution Order: ", " → ".join(execution_order))
print("\n{:<8} {:<8} {:<8} {:<8} {:<12} {:<12} {:<12}".format(
    "Process", "Arrival", "Burst", "Start", "Completion", "Turnaround", "Waiting"
))
for p in completed:
    print("{:<8} {:<8} {:<8} {:<8} {:<12} {:<12} {:<12}".format(
        p["name"], p["arrival"], p["burst"], p["start"],
        p["completion"], p["turnaround"], p["waiting"]
    ))