# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ikIsCSRO6bNlpbxlImGq6hUQ9V4U2kPF
"""

requests = [137, 240, 179, 75, 118, 29, 15, 51]
head = 55
seek_sequence = []
total_seek = 0

print("Step-by-step SSTF Execution:\n")
step = 1
while requests:

    next_request = min(requests, key=lambda x: abs(head - x))
    seek = abs(head - next_request)
    total_seek += seek
    print(f"Step {step}: From {head} to {next_request} → Seek = {seek}")
    seek_sequence.append((head, next_request, seek))
    head = next_request
    requests.remove(next_request)
    step += 1

print(f"\nTotal Seek Operations = {total_seek}")

